// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1ed9300d-a962-4322-8736-67fdc37b0fdb",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "3460da9e6b524e188034f2e37740f2de",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "licketysplit-20181010180705--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://licketysplit-20181010180705--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://xscavx6ronacfb3vzs3anfnrri.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ylzhastb6fgcnj3bomu5ui62ua"
};


export default awsmobile;
