// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1ed9300d-a962-4322-8736-67fdc37b0fdb",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "3460da9e6b524e188034f2e37740f2de",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
